email_domains = [
    "gmail.com", "yahoo.com", "hotmail.com", "aol.com", "msn.com", "outlook.com", "icloud.com",
    "mail.com", "yandex.ru", "mail.ru", "rambler.ru", "bk.ru", "inbox.ru", "list.ru", "protonmail.com",
    "zoho.com", "gmx.com", "tutanota.com", "yahoo.co.uk", "yahoo.fr", "yahoo.de", "yahoo.co.jp",
    "yahoo.ca", "yahoo.es", "yahoo.it", "yahoo.in", "comcast.net", "verizon.net", "bellsouth.net",
    "att.net", "earthlink.net", "cox.net", "sbcglobal.net", "charter.net", "optonline.net",
    "me.com", "mac.com", "icloud.com", "fastmail.com", "hushmail.com", "inbox.com", "gmx.co.uk",
    "rediffmail.com", "lycos.com", "rocketmail.com", "ymail.com", "aim.com", "ntlworld.com",
    "btinternet.com", "live.com", "live.co.uk", "live.ca", "live.fr", "live.de", "live.in", "live.nl",
    "live.it", "hotmail.co.uk", "hotmail.fr", "hotmail.it", "hotmail.de", "hotmail.co.jp",
    "q.com", "sympatico.ca", "rogers.com", "shaw.ca", "ntlworld.com", "talktalk.net", "virgin.net",
    "blueyonder.co.uk", "bt.com", "freeserve.co.uk", "plus.com", "sky.com", "ntl.com", "nildram.co.uk",
    "zen.co.uk", "dsl.pipex.com", "demon.co.uk", "onidc.com", "chello.nl", "ziggo.nl", "wanadoo.fr",
    "orange.fr", "tele2.nl", "free.fr", "laposte.net", "sfr.fr", "neuf.fr", "tiscali.fr", "gmx.fr",
    "libero.it", "tim.it", "alice.it", "virgilio.it", "tiscali.it", "email.it", "fastwebnet.it",
    "tin.it", "interfree.it", "teletu.it", "vodafone.it", "nate.com", "hanmail.net", "daum.net",
    "kakao.com", "naver.com", "empas.com", "korea.com", "paran.com", "mail.com", "gmx.net",
    "web.de", "t-online.de", "freenet.de", "alice.de", "arcor.de", "aon.at", "chello.at", "gmx.at",
    "yahoo.at", "yahoo.be", "skynet.be", "telenet.be", "scarlet.be", "voo.be", "mail.be", "belgacom.be",
    "adinet.com.uy", "montevideo.com.uy", "telemar.com.br", "oi.com.br", "ig.com.br", "itelefonica.com.br",
    "terra.com.br", "uol.com.br", "yahoo.com.br", "bol.com.br", "globo.com", "globomail.com",
    "superig.com.br", "ig.com.br", "zipmail.com.br", "click21.com.br", "netcabo.pt", "clix.pt",
    "sapo.pt", "telepac.pt", "net.pt", "mail.pt", "vodafone.pt", "meo.pt", "yahoo.pt", "orange.pl",
    "wp.pl", "onet.pl", "op.pl", "interia.pl", "poczta.fm", "o2.pl", "gazeta.pl", "home.pl",
    "poczta.onet.pl", "mail.com.pl", "seznam.cz", "volny.cz", "centrum.cz", "atlas.cz", "email.cz",
    "post.cz", "quick.cz", "chello.cz", "tiscali.cz", "gmx.ch", "bluewin.ch", "freesurf.ch",
    "green.ch", "hispeed.ch", "gmx.at", "yahoo.com.au", "bigpond.com", "bigpond.net.au", "optusnet.com.au",
    "internode.on.net", "tpg.com.au", "iinet.net.au", "ozemail.com.au", "westnet.com.au", "dodo.com.au",
    "vodafone.com.au", "three.com.au", "xtra.co.nz", "yahoo.co.nz", "paradise.net.nz", "clear.net.nz"
]
